//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoRaReceiver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public System.DateTime ReceivedTime { get; set; }
        public int RSSI { get; set; }
        public double SNR { get; set; }
        public int SpreadingFactor { get; set; }
        public string MessageContents { get; set; }
        public Nullable<double> BatteryVoltage { get; set; }
    }
}
